app1/urls.py
from app1.views import *

from django.urls import path

app_name='something'

urlpatterns=[
    path('harish/',harish,name='harish'),
 ]

app2/urls.py
from app2.views import *

from django.urls import path

app_name='nothing'


urlpatterns=[
    path('response/',response,name='response'),
 ]

project14/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.

def harish(request):
    return render(request,'harish.html')

app2/views.py
from django.shortcuts import render

# Create your views here.


def response(request):
    return render(request,'response.html')

templates/harish.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center> 
        <h1> hello </h1>
        <h1> how atre you </h1>
         <a href="{% url 'nothing:response' %}"><h2>to click here</h2></a>
    </center>
    
</body>
</html>

templates/response.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1> i am fine    </h1>
        <h1>how are you</h1>
        <a href="{% url 'something:harish' %}"> <h1>naviage to harish</h1></a>
    </center>
    
</body>
</html>